services:
  kanboard:
    image: kanboard/kanboard:latest
    container_name: Kanboard
    ports:
      - ${PORT}:80
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
    environment:
      - PLUGIN_INSTALLER=true
      - ENABLE_XFRAME=false #set to true to block using iframes
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:80/ || exit 1
    restart: always
    
volumes:
  kanboard_data:
  kanboard_plugins:
